language: java
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a143efa81f451ac87182
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
after_success:
- ./gradlew jacocoTestReport coveralls

